# Generated by Django 5.2.8 on 2025-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_user_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["mobile"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
